### 엑셀데이타 읽어오기

pandasm 이용 엑셀 데이타 가져오기 (결과: DataFrame )

In [1]:
import pandas as pd
import xlwings as xw

In [2]:
#  pandas 이용 엑셀 데이타 가져오기 (결과: DataFrame )
pd.read_excel('data/top100.xlsx')
df = pd.read_excel('data/top100.xlsx', index_col='id')
df.head()

,album_name,artist_name,name,좋아요
id,,,,
31093710,Red Diary Page.2,볼빨간사춘기,여행,124968
31085237,LOVE YOURSELF 轉 `Tear`,방탄소년단,FAKE LOVE,200654
31113240,1÷χ=1 (UNDIVIDED),Wanna One (워너원),켜줘 (Light),93035
31113241,1÷χ=1 (UNDIVIDED),Wanna One (워너원) - 트리플포지션,캥거루 (Kangaroo) (Prod. ZICO),79320
31113243,1÷χ=1 (UNDIVIDED),Wanna One (워너원) - 더힐,모래시계 (Prod. 헤이즈),67872

In [14]:
# 새로운 컬럼 추가
# df['테스트'] # 에러발생
df['테스트']=10 # 전부 10으로 생성
df.head()
df['테스트']=range(1,101,1) # 1부터 100까지 차례대로 생성
# df['테스트']=range(1,100,1) # 개수가 안맞아서 에러 발생
df.head()
df.tail()

,album_name,artist_name,name,좋아요,테스트
id,,,,,
31123659,`The Story of Light` EP.2 - The 6th Album,SHINee (샤이니),독감 (Who Waits For Love),12730,96
30086173,LIFE IS BEAUTY FULL,문문 (MoonMoon),비행운,202347,97
30383758,종현 소품집 `이야기 Op.2`,종현 (JONGHYUN),Lonely (Feat. 태연),180606,98
30481578,마지막처럼,BLACKPINK,마지막처럼,159147,99
30380953,Illuminate (New Deluxe Ver.),Shawn Mendes,There`s Nothing Holdin` Me Back,107309,100

### DataFrame 에서 컬럼 삭제

In [4]:
# df.drop?
df.drop(31093710)
df.head() 
""" 안지워지는데? 결과 데이타셋으로 대치해야한다.

    df = df.drop(31093710)
    df.drop(31093710, inplace=True)
"""

' 안지워지는데?\n    df = df.drop(31093710)\n    df.drop(31093710, inplace=True)\n'

In [16]:
# 컬럼으로 삭제하려면?
# df = df.drop('테스트') # 에러 발생
# df.head()


df.drop('테스트', axis=1) # 컬럼임을 지정해야 함 (0:index, 1:column)
# df.drop('테스트')         # 에러 : axis=0 기본값

# df.drop(columns='테스트') # columns으로 컬럼명 지정

,album_name,artist_name,name,좋아요
id,,,,
31093710,Red Diary Page.2,볼빨간사춘기,여행,124968
31085237,LOVE YOURSELF 轉 `Tear`,방탄소년단,FAKE LOVE,200654
31113240,1÷χ=1 (UNDIVIDED),Wanna One (워너원),켜줘 (Light),93035
31113241,1÷χ=1 (UNDIVIDED),Wanna One (워너원) - 트리플포지션,캥거루 (Kangaroo) (Prod. ZICO),79320
31113243,1÷χ=1 (UNDIVIDED),Wanna One (워너원) - 더힐,모래시계 (Prod. 헤이즈),67872
30699142,About You,닐로 (Nilo),지나오다,138400
30960341,0+1=1 (I PROMISE YOU),Wanna One (워너원),BOOMERANG (부메랑),116807
31113242,1÷χ=1 (UNDIVIDED),Wanna One (워너원) - 린온미,영원+1 (Prod. NELL),65062
31052421,여자친구 The 6th Mini Album 'Time for the moon night',여자친구 (GFRIEND),밤 (Time for the moon night),97009
31085238,LOVE YOURSELF 轉 `Tear`,방탄소년단,전하지 못한 진심 (Feat. Steve Aoki),129126
31113244,1÷χ=1 (UNDIVIDED),Wanna One (워너원) - 남바완,11 (Prod. 다이나믹듀오),59050
30568338,1X1=1(TO BE ONE),Wanna One (워너원),에너제틱 (Energetic),260417
31035061,건반 위의 하이에나 Part.4,화사 (마마무),주지마,128631
31098083,BINGLE BANGLE,AOA,빙글뱅글 (Bingle Bangle),48776
30725482,1-1=0 (NOTHING WITHOUT YOU),Wanna One (워너원),Beautiful,211145
30637982,LOVE YOURSELF 承 `Her`,방탄소년단,DNA,301340
31085244,LOVE YOURSELF 轉 `Tear`,방탄소년단,Anpanman,107561
30930312,0+1=1 (I PROMISE YOU),Wanna One (워너원),약속해요 (I.P.U.),131864
30244931,YOU NEVER WALK ALONE,방탄소년단,봄날,330623
31085243,LOVE YOURSELF 轉 `Tear`,방탄소년단,Airplane pt.2,102741
31085240,LOVE YOURSELF 轉 `Tear`,방탄소년단,낙원,102395
31085242,LOVE YOURSELF 轉 `Tear`,방탄소년단,Magic Shop,106310
31085241,LOVE YOURSELF 轉 `Tear`,방탄소년단,Love Maze,101755
30849733,투유 프로젝트 - 슈가맨2 Part.2,멜로망스,You,118037
31085239,LOVE YOURSELF 轉 `Tear`,방탄소년단,134340,102354
30962526,`키스 먼저 할까요?` OST Part.3,폴킴,"모든 날, 모든 순간 (Every day, Every Moment)",68254
31085245,LOVE YOURSELF 轉 `Tear`,방탄소년단,So What,93015
31006730,What is Love?,TWICE (트와이스),What is Love?,106473
31055324,I am,(여자)아이들,LATATA,57736
31123630,The Feeling,비투비,The Feeling,41494
...,...,...,...,...
31009486,Blooming Days - The 2nd Mini Album,EXO-CBX (첸백시),Vroom Vroom,54477
30864993,The Perfect Red Velvet - The 2nd Album Repackage,Red Velvet (레드벨벳),Bad Boy,136666
30341745,FATE NUMBER FOR,WINNER,REALLY REALLY,193439
31009484,Blooming Days - The 2nd Mini Album,EXO-CBX (첸백시),내일 만나 (Sweet Dreams!),53263
30939452,바람,헤이즈 (Heize),Jenga (Feat. Gaeko),82513
31093714,Red Diary Page.2,볼빨간사춘기,Lonely,26385
30492279,/// (너 먹구름 비),헤이즈 (Heize),비도 오고 그래서 (Feat. 신용재),205030
30690674,REMEMBER ME,포맨,눈 떠보니 이별이더라,72019
31009482,Blooming Days - The 2nd Mini Album,EXO-CBX (첸백시),Monday Blues,58157
30781481,Merry & Happy,TWICE (트와이스),Heart Shaker,119938
31009488,Blooming Days - The 2nd Mini Album,EXO-CBX (첸백시),휴일 (Lazy),52851
30550388,0M,박원,all of my life,176223
30957524,고등래퍼2 팀대항전 Part.1,오담률 (CHIN CHILLA),북 (Prod. SLO),79289
30877002,그리고 봄,정승환,눈사람,111826
31009485,Blooming Days - The 2nd Mini Album,EXO-CBX (첸백시),Thursday,52756
30512671,The Red Summer - Summer Mini Album,Red Velvet (레드벨벳),빨간 맛 (Red Flavor),188765
30486509,LISTEN 010 좋니,윤종신,좋니,308934
7928705,Blue Neighbourhood (Deluxe),Troye Sivan,YOUTH,123680
30613202,시차 (We Are),우원재,시차 (We Are) (Feat. 로꼬 & GRAY),229523
30806580,instagram,DEAN,instagram,161477
31097924,`The Story of Light` EP.1 - The 6th Album,SHINee (샤이니),All Day All Night,22210
31019586,고등래퍼2 Final,빈첸 (VINXEN),전혀 (Feat. 우원재) (Prod. GroovyRoom),62172
30700708,twicetagram,TWICE (트와이스),LIKEY,122060
31126160,Playlist,DPR LIVE,Playlist,9431
30985406,나의 아저씨 OST Part.2,Sondia,어른,47994
31123659,`The Story of Light` EP.2 - The 6th Album,SHINee (샤이니),독감 (Who Waits For Love),12730
30086173,LIFE IS BEAUTY FULL,문문 (MoonMoon),비행운,202347
30383758,종현 소품집 `이야기 Op.2`,종현 (JONGHYUN),Lonely (Feat. 태연),180606
30481578,마지막처럼,BLACKPINK,마지막처럼,159147
30380953,Illuminate (New Deluxe Ver.),Shawn Mendes,There`s Nothing Holdin` Me Back,107309

###  데이타프레임 합치기

1. append()

2. concat()

In [6]:
df1 = pd.read_excel('data/2016-01.xls', index_col='상품명')
print(df1.shape)
print(df1.head())
df2 = pd.read_excel('data/2016-02.xls', index_col='상품명')
print(df1.shape)
print(df2.head())

(200, 3)
       판매건수     가격       매출2
상품명
봉투    12362     50    618100
바나나    4285   3900  16711500
야채     4190      0         0
켐벨포도   2780  29800  82844000
알뜰특란   2768   5300  14670400
(200, 3)
       판매건수     가격
상품명
봉투    10519     50
바나나    3123   3900
야채     2975      0
켐벨포도   2344  29800
알뜰특란   2242   5300

In [7]:
df1 + df2 # 각가의 인덱스별로 매칭만 하기에 의미 없음

                        가격  매출2    판매건수
상품명
CJ)안심종합어묵              NaN  NaN     NaN
CJ)얇은사각어묵              NaN  NaN     NaN
CJ)주부초밥왕(소풍)           NaN  NaN     NaN
CJ)행복한콩(고소부침)       2960.0  NaN  1259.0
CJ)행복한콩(고소찌게)       2960.0  NaN  1197.0
CJ)행콩나물                NaN  NaN     NaN
가지                     NaN  NaN     NaN
감귤                     0.0  NaN  1486.0
감귤                 29800.0  NaN  1241.0
감귤                  4500.0  NaN  1089.0
감귤                 28000.0  NaN  1034.0
감귤                  4500.0  NaN   982.0
감귤                 34300.0  NaN   737.0
감귤                  9000.0  NaN   585.0
감귤                 32500.0  NaN   530.0
감귤                 29800.0  NaN   964.0
감귤                 59600.0  NaN   719.0
감귤                 34300.0  NaN   567.0
감귤                 57800.0  NaN   512.0
감자                     0.0  NaN  2432.0
강릉심층수팩두부            4000.0  NaN   988.0
강릉초당)고소한두부(찌개용)     3000.0  NaN  1843.0
강릉초당)봉지두부           3000.0  NaN  1483.0
강릉초당)왕콩나물           3900.0  NaN  3347.0
거봉                 13800.0  NaN  1480.0
건미역(산모용)            7600.0  NaN   515.0
곰표)밀가루                 NaN  NaN     NaN
광동)삼다수(대)           2000.0  NaN  1678.0
광동)삼다수(소)           1000.0  NaN   890.0
그린키위                   NaN  NaN     NaN
...                    ...  ...     ...
풀)소가/찌개두부           2200.0  NaN  1828.0
풀)액티비아컵(딸기)         4700.0  NaN   958.0
풀)액티비아컵(플레인)        4700.0  NaN  1032.0
풀)하루에한알                NaN  NaN     NaN
풋고추                    NaN  NaN     NaN
피망                     NaN  NaN     NaN
하림닭도리탕(국내산)            NaN  NaN     NaN
한돈다짐육(국내산)             NaN  NaN     NaN
한돈등심/카레(국내산)           NaN  NaN     NaN
한돈목살구이(국내산)            0.0  NaN   812.0
한돈불고기(국내산)             NaN  NaN     NaN
한돈삼겹살(국내산)             0.0  NaN  1188.0
한돈앞다리/불고기,찌개(국내산)      NaN  NaN     NaN
한돈오겹살(국내산)             NaN  NaN     NaN
한성)런천미트                NaN  NaN     NaN
한성)미니윈너             8700.0  NaN   518.0
한성)비바크부어스트          9300.0  NaN   705.0
한성)튀김우동                NaN  NaN     NaN
한성)해물우동             2900.0  NaN   518.0
한우양지국거리(국내산)           0.0  NaN  1445.0
해)오예스(딸기)              NaN  NaN     NaN
해)킨사이다                 NaN  NaN     NaN
해태)오예스                 NaN  NaN     NaN
해표)고소한참기름              NaN  NaN     NaN
해표)식용유                 NaN  NaN     NaN
해표)카놀라유            11200.0  NaN   603.0
허니미니꿀호떡                NaN  NaN     NaN
호박고구마                  0.0  NaN   523.0
황도복숭아                  0.0  NaN   550.0
흙당근                    0.0  NaN  1300.0

[264 rows x 3 columns]

In [17]:
# 1. append()
# df1.append(df2) # 정렬관련 warning
df1.append(df2, sort=True) # warning 없어짐

df3 = df1.append(df2, sort=True)
print(df3.shape)
df3.head()

(400, 3)

         가격         매출2   판매건수
상품명
봉투       50    618100.0  12362
바나나    3900  16711500.0   4285
야채        0         0.0   4190
켐벨포도  29800  82844000.0   2780
알뜰특란   5300  14670400.0   2768

In [9]:
# 2. concat()
# pd.concat([df1,df2], axis='index')
df4 =pd.concat([df1,df2], axis='index', sort=True)
print(df4.shape)
df4.head()

(400, 3)

         가격         매출2   판매건수
상품명
봉투       50    618100.0  12362
바나나    3900  16711500.0   4285
야채        0         0.0   4190
켐벨포도  29800  82844000.0   2780
알뜰특란   5300  14670400.0   2768